import '../models/enums.dart';
import '../models/report.dart';

/// Report-generation fixtures.
abstract final class MockReports {
  static const workspace = ReportsWorkspace(
    generatorHeading: 'Generate new PDF report',
    selectedTypeId: 'revenue',
    types: [
      ReportType(
        id: 'revenue',
        label: 'Revenue & Financial',
        description: 'P&L, transactions, refunds',
        iconKey: 'money',
        tintHue: 145,
      ),
      ReportType(
        id: 'bookings',
        label: 'Bookings Summary',
        description: 'Reservations, cancellations',
        iconKey: 'calendar',
        tintHue: 215,
      ),
      ReportType(
        id: 'trainers',
        label: 'Trainer Performance',
        description: 'Ratings, sessions, revenue',
        iconKey: 'dumbbell',
        tintHue: 30,
      ),
      ReportType(
        id: 'members',
        label: 'Member Activity',
        description: 'Retention, churn, growth',
        iconKey: 'users',
        tintHue: 280,
      ),
      ReportType(
        id: 'locations',
        label: 'Locations Report',
        description: 'By gym, by city',
        iconKey: 'pin',
        tintHue: 5,
      ),
      ReportType(
        id: 'custom',
        label: 'Custom Report',
        description: 'Build your own with filters',
        iconKey: 'plus',
        tintHue: 195,
      ),
    ],
    parameters: [
      ReportParameter(
        label: 'Date range',
        value: 'Apr 1 – Apr 25, 2026',
        isRequired: true,
      ),
      ReportParameter(label: 'Format', value: 'PDF (recommended)'),
      ReportParameter(label: 'Locations', value: 'All 4 locations'),
      ReportParameter(label: 'Group by', value: 'By trainer'),
    ],
    sectionsHeading: 'Include sections',
    sections: [
      ReportSectionToggle(label: 'Executive summary', enabledByDefault: true),
      ReportSectionToggle(label: 'Revenue chart', enabledByDefault: true),
      ReportSectionToggle(label: 'Top trainers', enabledByDefault: true),
      ReportSectionToggle(label: 'Booking heatmap', enabledByDefault: true),
      ReportSectionToggle(label: 'Refunds detail', enabledByDefault: false),
      ReportSectionToggle(label: 'Tax breakdown', enabledByDefault: true),
      ReportSectionToggle(label: 'Per-location P&L', enabledByDefault: false),
    ],
    saveTemplateLabel: 'Save as template',
    generateLabel: 'Generate PDF',
    preview: ReportPreview(
      eyebrow: 'FITBOOK · MONTHLY REPORT',
      title: 'Revenue & Financial',
      periodLabel: 'Period: Apr 1 – Apr 25, 2026',
      figures: [('Total revenue', '48,320 KM'), ('Sessions', '1,074')],
      footer:
          'Page 1 of 14 · Generated by FitBook Admin · '
          'selma.bektas@fitbook.ba',
    ),
    historyHeading: 'Recent reports',
    history: [
      GeneratedReport(
        name: 'Monthly Revenue Report — April 2026',
        type: 'Financial',
        sizeLabel: '2.4 MB',
        dateLabel: 'Apr 25, 14:02',
        state: ReportState.ready,
      ),
      GeneratedReport(
        name: 'Trainer Performance Q1 2026',
        type: 'Performance',
        sizeLabel: '4.1 MB',
        dateLabel: 'Apr 22, 09:30',
        state: ReportState.ready,
      ),
      GeneratedReport(
        name: 'Member Retention Analysis',
        type: 'Analytics',
        sizeLabel: '1.8 MB',
        dateLabel: 'Apr 18, 11:14',
        state: ReportState.ready,
      ),
      GeneratedReport(
        name: 'Bookings Summary — March 2026',
        type: 'Operations',
        sizeLabel: '3.2 MB',
        dateLabel: 'Apr 02, 08:00',
        state: ReportState.ready,
      ),
      GeneratedReport(
        name: 'Tax Report — Q1 2026',
        type: 'Financial',
        sizeLabel: 'Generating…',
        dateLabel: 'Just now',
        state: ReportState.generating,
      ),
    ],
  );

  static const previewHeading = 'Live preview';
  static const viewAllLabel = 'View all';
  static const newReportLabel = 'New report';
}
